main: com.olliez4.captcha.ReCaptchaPlugin
name: reCaptcha
description: A simple, non-invasive and easy to use Captcha GUI for Spigot Minecraft servers. Imagined and developed by OLLIEZ4 for the sole purpose of not losing players to annoying and repetitive forced GUI's which intrude with their playtime and overall experience.
version: ${project.version}
authors: [OLLIEZ4]
api-version: 1.17
